version: "3.7"

services:

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ubuntu/prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - /var/run/docker.sock:/var/run/docker.sock # Docker 소켓 마운트
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: always
    user: "0" # root 사용자로 설정
    privileged: true
    networks:
      - katecam-backend  # 네트워크 추가

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/grafana/conf_grafana:/config_files
    restart: always
    depends_on:
      - prometheus
    privileged: true
    networks:
      - katecam-backend  # 네트워크 추가

# 네트워크 정의
networks:
  katecam-backend:
    external: true  # 기본적으로 bridge 네트워크 사용

