# my global config
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: "prometheus"

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ["localhost:9090"]
  
  # 카테캠 첫번째 서버 (BLUE)
  - job_name: "katecam-backend-first-first"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["3.34.0.32:8080"]
  # 카테캠 첫번째 서버 (GREE)
  - job_name: "katecam-backend-first-second"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["3.34.0.32:8081"]

  # 카테캠 두번째 서버 (BLUE)
  - job_name: "katecam-backend-second-first"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["3.35.66.77:8080"]
  # 카테캠 두번째 서버 (GREEN)
  - job_name: "katecam-backend-second-second"
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["3.35.66.77:8081"]

  # NGINX Exporter 를 위한 설정 추가
  - job_name: "nginx"
    metrics_path: "/metrics"
    scrape_interval: 10s
    static_configs:
      - targets: ["nginx-exporter:9113"] # NGINX Exporter 컨테이너 이름을 사용
