services:
  api:
    image: bomul0524/katecam-backend:latest
    container_name: katecam-backend-first
    environment:
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8080
    ports:
      - '8080:8080'
    networks:
      - katecam-backend

networks:
  katecam-backend:
    external: true
